// Generated by CoffeeScript 1.7.1
var AutomataUtils;

AutomataUtils = (function() {
  function AutomataUtils() {}

  AutomataUtils.buildGraphModel = function(model) {
    var graph, k, l, ls, t, v, _i, _j, _len, _len1, _ref, _ref1;
    graph = {
      nodes: [],
      links: {}
    };
    _ref = model.nodes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      nodes.push(v);
    }
    _ref1 = model.links;
    for (k in _ref1) {
      ls = _ref1[k];
      if (!getNodeById(graph.nodes, k != null)) {
        console.log("Undefined State " + k);
        continue;
      }
      for (_j = 0, _len1 = ls.length; _j < _len1; _j++) {
        l = ls[_j];
        if (links[k] == null) {
          links[k] = [];
        }
        t = getNodeById(graph.nodes, l.target);
        if (t == null) {
          console.log("Undefined State " + t);
          continue;
        }
        links[k].push({
          trigger: l.trigger,
          target: t
        });
      }
    }
  };

  AutomataUtils.getNodeById = function(nodes, id) {
    var n, _i, _len;
    for (_i = 0, _len = nodes.length; _i < _len; _i++) {
      n = nodes[_i];
      if (n.id === id) {
        return n;
      }
    }
    return void 0;
  };

  return AutomataUtils;

})();
