// Generated by CoffeeScript 1.7.1
var EventDispatcher;

EventDispatcher = function() {
  var _fnMap;
  _fnMap = [];
  this.on = function(fn) {
    _fnMap.push(fn);
  };
  this.remove = function(fn) {
    if (_fnMap.contains(fn)) {
      return _fnMap.pop(fn);
    }
  };
  this.trigger = function(evt) {
    var fn, _i, _len;
    for (_i = 0, _len = _fnMap.length; _i < _len; _i++) {
      fn = _fnMap[_i];
      fn(evt);
    }
  };
};
